on:
  push:
  release:
    types: [created]
jobs:
  docker:
    uses: "midgardhero/cicd_centralizado/.github/workflows/docker_build.yaml@pipeline_docker"
    with:
      image: midgardhero/imagem_teste:latest
      push_image: ${{github.event_name == 'release'}}
    secrets:
      docker_user: ${{secrets.DOCKER_LOGIN}}
      docker_password: ${{secrets.TOKEN_DOCKERHUB}}
