on:
  push:
  release:
    types: [created]
jobs:
  docker:
    uses: "midgardhero/cicd_centralizado/.github/workflows/docker_build.yaml@pipeline_docker"
    with:
      tag: imagem_teste
      trivy_ignore: |
        CVE-2020-36518
      push_image: ${{github.event_name == 'release'}}
      docker_user: ${{secrets.DOCKER_LOGIN}}
      docker_password: ${{secrets.TOKEN_DOCKERHUB}}
