on:
  push:
jobs:
  docker:
    uses: "midgardhero/cicd_centralizado/.github/workflows/docker_build.yaml@pipeline_docker"
    with:
      tag: imagem_teste
      trivy_ignore_policy: |
        package trivy

        import data.lib.trivy

        default ignore = false

        ignore_severities := {"HIGH"}

        ignore {
          input.Severity == ignore_severities[_]
        }